# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Kaare' do

pod 'ReactiveCocoa', '~> 2.3.1'
pod 'JSCoreBom', '~> 1.1.1'

end

target 'KaareTests' do

pod 'ReactiveCocoa', '~> 2.3.1'
pod 'AGAsyncTestHelper', '~> 0.2.2'

end

